### ISSUE TITLE
Checker: Look for provider-metadata.json in all suggested places

### ISSUE THREAD

**Issue by Id3aFly** [csaf-poc/csaf_distribution#193] opened 2022-06-22 13:19 UTC
I was just trying out the csaf_checker. However, it is not able to find my provider-metadata.json file. 

The Framework description mentions in [chapter 7.1.7](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html#717-requirement-7-provider-metadatajson) 4 different possibilities where to place the provider-metadata.json.
However the csaf_checker only looks in 1 of the described places: [.well-known/csaf/provider-metadata.json](https://github.com/csaf-poc/csaf_distribution/blob/main/csaf/util.go#L138)

Would it be possible to add the other 3 locations as well?

**Comment by bernhardreiter** [comment] 2022-06-22 15:11
@Id3aFly thanks for trying out our checker.

> However the csaf_checker only looks in 1 of the described places: .well-known/csaf/provider-metadata.json

The current version follows the recommended steps in https://docs.oasis-open.org/csaf/csaf/v2.0/csd02/csaf-v2.0-csd02.html#731-finding-provider-metadatajson . 

If you run the checker with `--verbose` you'll get more info about where it is searching.

It is my understanding of CSAF 2.0 csd02 that if someone wants to put the `provider-metadata.json` at one of the non-canonical example places, then it must be made visible by other means, e.g. by putting the location into the `security.txt` (preferedy) or by using the DNS path method (if not possible otherwise).

However as we are still testing some things: If you send me a private message about which server you are trying, or the full output with `--verbose`, I'll take a look. You'll find my public OpenPGP  via WKD, see https://intevation.de/~bernhard

**Comment by bernhardreiter** [comment] 2022-06-24 11:33
@tschmidtb51 thanks for the confirmation. 

As it works as intended (so far), I'll close this issue.

**Closed by bernhardreiter** 2022-06-24 11:33 UTC
Labels: question
